<a href="https://colab.research.google.com/github/poorvika-03/Samsung-Innovation-Campus/blob/main/iris_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

from sklearn.datasets import load_iris

In [ ]:
df = load_iris()

In [ ]:
X = df.data

y = df.target

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
from sklearn.decomposition import PCA

from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
# Standardizing the data
X_scaled = scaler.fit_transform(X)

In [ ]:
X_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [ ]:
# Applying PCA
pca_iris = PCA()
pca_iris.fit(X_scaled)

PCA()

In [ ]:
# Explained variance ratio
explained_variance_X = pca_iris.explained_variance_ratio_

In [ ]:
explained_variance_X

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [ ]:
# Showing the components (loadings)
components_X = pd.DataFrame(pca_iris.components_,columns=df.feature_names)

In [ ]:
components_X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.521066         -0.269347           0.580413          0.564857
1           0.377418          0.923296           0.024492          0.066942
2           0.719566         -0.244382          -0.142126         -0.634273
3          -0.261286          0.123510           0.801449         -0.523597

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Fitting the Random Forest model
rf_classifier = RandomForestClassifier()

In [ ]:
rf_classifier.fit(X, y)

RandomForestClassifier()

In [ ]:
rf_classifier.feature_importances_

array([0.07845942, 0.02023002, 0.42468972, 0.47662084])

In [ ]:
importances_iris =rf_classifier.feature_importances_

In [ ]:
# Creating a DataFrame for feature importances
feature_importance_iris_df = pd.DataFrame({
    'Feature': df.feature_names,
    'Importance': importances_iris
}).sort_values(by='Importance', ascending=False)

In [ ]:
feature_importance_iris_df

Feature  Importance
3   petal width (cm)    0.476621
2  petal length (cm)    0.424690
0  sepal length (cm)    0.078459
1   sepal width (cm)    0.020230